module.exports.userService=require('./user.service')
module.exports.emailService=require('./email.service')
module.exports.productService=require('./product.service')
module.exports.orderService=require('./order.service')
module.exports.cartService=require('./cart.service')